### PR TITLE
Replace gaze with chokidar, add yarn.lock

### PR DESCRIPTION
**Pull request by vyorkin**
[gaze](https://github.com/shama/gaze) doesn't work for me (I'm on mac os x Sierra) for some reason.

here is the repo demonstrating issue with gaze: [vyorkin-play/gaze-watch-example](https://github.com/vyorkin-play/gaze-watch-example),
but chokidar works just fine: [vyorkin-play/chokidar-watch-example](https://github.com/vyorkin-play/chokidar-watch-example)

 I wasn't able to dive deeper than that so I can't tell for sure what the exact problem is.

about yarn.lock: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all

### CODE REVIEW

**Comment by vyorkin** [comment]
hey @Quramy! were you to reproduce the issue?

**Comment by vyorkin** [comment]
@Quramy do you need help supporting this project? I can take over it if you don't mind :P

**Comment by Quramy** [comment]
Sorry for my reviewing and merging. And thanks for your PR :)

**Comment by vyorkin** [comment]
thanks @Quramy !

**Pull request merged**
