### PR TITLE
Cleanup, async/await & let/const

### PR DESCRIPTION
**Pull request by gdelmas**
hi @Quramy,

i made some further changes. mainly to async/await. but also some cleanup and the use of let/const.

for review it is probably worth looking at the changes at each commit one by one, as they are not a lot. the whole diff looks overwhelming and is not reflecting the steps well.

### CODE REVIEW

**Comment by gdelmas** [comment]
ahhh, i just noticed `utils.promisify` is not available in node 6. so test is failing. i will do a custom promisification.

would you generally be open to the changes? i think it is nice as it reduces the lines of code, by keeping the functionality.

**Comment by gdelmas** [comment]
hey @Quramy,

what do you think about async/await?

**Comment by Quramy** [comment]
@gdelmas Sorry for my late reply :bow:

I like async/await syntax too.

And for now unit testing is run in Node.js v6 env, but I think almost dev uses Node >= v8. So we no longer need to support v6.

**Comment by Quramy** [comment]
You can remove https://github.com/Quramy/typed-css-modules/blob/master/.travis.yml#L9 and use promisify.

**Comment by gdelmas** [comment]
hey @Quramy,

great to hear from you and happy you also like async/await better. you are completely right, without node6 support there is less code to maintain. i added a new commit to remove node6 support, where i also added the required node version to `package.json` so that some developer installing this might get a warning. i kept the commit with node6 support in the history, in case someone needs it and wants to fork.

**Comment by Quramy** [comment]
Thanks for your great work!!!

**Comment by Quramy** [comment]
I've published this as v0.5.0 🎉

**Comment by gdelmas** [comment]
amazing, thanks @Quramy

**Pull request merged**
