### PR TITLE
Add silent output option

### LINKED ISSUE #37: Any way to disable warnings in CLI?
Would be helpful to me.

### PR DESCRIPTION
**Pull request by gdelmas**
this closes #37

### CODE REVIEW

**Comment by gdelmas** [comment]
Hey @Quramy,

is this small option something you would consider merging? Otherwise I will fork.

Thanks,
Gerard

**Comment by Quramy** [comment]
Sorry for my late merge :bow: and thanks for your PR:)

**Comment by Quramy** [comment]
Yeah, I’ll publish this via 0.3.4 after I get back my home :+1: 
pls wait some minutes :pray:

**Comment by gdelmas** [comment]
thanks @Quramy. no stress. we are happy to get rid of a lot of noise from our CI logs.

**Pull request merged**
